var maleOpenTopsIds = [
    3, 4, 7, 23, 29, 31, 35,
    58, 59, 77, 99, 103, 106,
    127, 130, 136, 142, 156,
    157, 160, 163, 166, 167,
    169, 170, 172, 173, 179,
    185, 189, 191, 192, 212
];

var maleOpenTops = [];
for (var i = 0; i < maleOpenTopsIds.length; i++)
{
    var variations = [
        { variation: maleOpenTopsIds[i], undershirt: 0, torso: 1, texture: 0 },
        { variation: maleOpenTopsIds[i], undershirt: 1, torso: 1, texture: 0 },
        { variation: maleOpenTopsIds[i], undershirt: 5, torso: 1, texture: 0 },
        { variation: maleOpenTopsIds[i], undershirt: 8, torso: 1, texture: 0 },
        { variation: maleOpenTopsIds[i], undershirt: 9, torso: 1, texture: 0 },
        { variation: maleOpenTopsIds[i], undershirt: 11, torso: 1, texture: 0 },
        { variation: maleOpenTopsIds[i], undershirt: 12, torso: 1, texture: 0 },
        { variation: maleOpenTopsIds[i], undershirt: 13, torso: 1, texture: 0 },
        { variation: maleOpenTopsIds[i], undershirt: 16, torso: 1, texture: 0 },
        { variation: maleOpenTopsIds[i], undershirt: 23, torso: 1, texture: 0 },
        { variation: maleOpenTopsIds[i], undershirt: 25, torso: 1, texture: 0 },
        { variation: maleOpenTopsIds[i], undershirt: 26, torso: 1, texture: 0 },
        { variation: maleOpenTopsIds[i], undershirt: 27, torso: 1, texture: 0 },
        { variation: maleOpenTopsIds[i], undershirt: 29, torso: 1, texture: 0 },
        { variation: maleOpenTopsIds[i], undershirt: 31, torso: 1, texture: 0 },
        { variation: maleOpenTopsIds[i], undershirt: 32, torso: 1, texture: 0 },
        { variation: maleOpenTopsIds[i], undershirt: 37, torso: 1, texture: 0 },
        { variation: maleOpenTopsIds[i], undershirt: 38, torso: 1, texture: 0 },
        { variation: maleOpenTopsIds[i], undershirt: 43, torso: 1, texture: 0 },
        { variation: maleOpenTopsIds[i], undershirt: 45, torso: 1, texture: 0 },
        { variation: maleOpenTopsIds[i], undershirt: 46, torso: 1, texture: 0 },
        { variation: maleOpenTopsIds[i], undershirt: 47, torso: 1, texture: 0 },
        { variation: maleOpenTopsIds[i], undershirt: 51, torso: 1, texture: 0 },
        { variation: maleOpenTopsIds[i], undershirt: 52, torso: 1, texture: 0 },
        { variation: maleOpenTopsIds[i], undershirt: 53, torso: 1, texture: 0 },
        { variation: maleOpenTopsIds[i], undershirt: 57, torso: 1, texture: 0 },
        { variation: maleOpenTopsIds[i], undershirt: 64, torso: 1, texture: 0 },
        { variation: maleOpenTopsIds[i], undershirt: 75, torso: 1, texture: 0 },
        { variation: maleOpenTopsIds[i], undershirt: 76, torso: 1, texture: 0 },
        { variation: maleOpenTopsIds[i], undershirt: 96, torso: 1, texture: 0 }
    ];
    maleOpenTops.push(variations);
}

var maleClosedTops = [
    { variation: 48, undershirt: 57, torso: 11, texture: 0 },
    { variation: 51, undershirt: 57, torso: 1, texture: 0 },
    { variation: 57, undershirt: 57, torso: 1, texture: 0 },
    { variation: 61, undershirt: 57, torso: 1, texture: 0 },
    { variation: 84, undershirt: 57, torso: 1, texture: 0 },
    { variation: 86, undershirt: 57, torso: 1, texture: 0 },
    { variation: 87, undershirt: 57, torso: 1, texture: 0 },
    { variation: 90, undershirt: 57, torso: 1, texture: 0 },
    { variation: 96, undershirt: 57, torso: 1, texture: 0 },
    { variation: 110, undershirt: 57, torso: 1, texture: 0 },
    { variation: 113, undershirt: 57, torso: 1, texture: 0 },
    { variation: 121, undershirt: 57, torso: 1, texture: 0 },
    { variation: 124, undershirt: 57, torso: 1, texture: 0 },
    { variation: 125, undershirt: 57, torso: 1, texture: 0 },
    { variation: 126, undershirt: 57, torso: 1, texture: 0 },
    { variation: 129, undershirt: 57, torso: 1, texture: 0 },
    { variation: 134, undershirt: 57, torso: 1, texture: 0 },
    { variation: 138, undershirt: 57, torso: 1, texture: 0 },
    { variation: 139, undershirt: 57, torso: 1, texture: 0 },
    { variation: 141, undershirt: 57, torso: 1, texture: 0 },
    { variation: 143, undershirt: 57, torso: 1, texture: 0 },
    { variation: 147, undershirt: 57, torso: 1, texture: 0 },
    { variation: 148, undershirt: 57, torso: 1, texture: 0 },
    { variation: 150, undershirt: 57, torso: 1, texture: 0 },
    { variation: 152, undershirt: 57, torso: 1, texture: 0 },
    { variation: 153, undershirt: 57, torso: 1, texture: 0 },
    { variation: 171, undershirt: 57, torso: 1, texture: 0 },
    { variation: 182, undershirt: 57, torso: 1, texture: 0 },
    { variation: 184, undershirt: 57, torso: 1, texture: 0 },
    { variation: 187, undershirt: 57, torso: 1, texture: 0 },
    { variation: 188, undershirt: 57, torso: 1, texture: 0 },
    { variation: 190, undershirt: 57, torso: 1, texture: 0 },
    { variation: 194, undershirt: 57, torso: 1, texture: 0 },
    { variation: 195, undershirt: 57, torso: 1, texture: 0 },
    { variation: 196, undershirt: 57, torso: 1, texture: 0 },
    { variation: 197, undershirt: 57, torso: 1, texture: 0 },
    { variation: 198, undershirt: 57, torso: 1, texture: 0 },
    { variation: 199, undershirt: 57, torso: 1, texture: 0 },
    { variation: 200, undershirt: 57, torso: 1, texture: 0 },
    { variation: 201, undershirt: 57, torso: 1, texture: 0 },
    { variation: 203, undershirt: 57, torso: 1, texture: 0 },
    { variation: 204, undershirt: 57, torso: 1, texture: 0 },
    { variation: 209, undershirt: 57, torso: 1, texture: 0 },
    { variation: 210, undershirt: 57, torso: 1, texture: 0 },
    { variation: 211, undershirt: 57, torso: 1, texture: 0 },
    { variation: 217, undershirt: 57, torso: 1, texture: 0 },
    { variation: 218, undershirt: 57, torso: 1, texture: 0 },
];

var maleShirts = [
    { variation: 0, undershirt: 57, torso: 0, texture: 0 },
    { variation: 1, undershirt: 57, torso: 0, texture: 0 },
    { variation: 2, undershirt: 57, torso: 0, texture: 0 },
    { variation: 5, undershirt: 57, torso: 113, texture: 0 },
    { variation: 8, undershirt: 57, torso: 8, texture: 0 },
    { variation: 9, undershirt: 57, torso: 0, texture: 0 },
    { variation: 11, undershirt: 57, torso: 21, texture: 0 },
    { variation: 12, undershirt: 57, torso: 12, texture: 0 },
    { variation: 13, undershirt: 57, torso: 0, texture: 0 },
    { variation: 14, undershirt: 57, torso: 1, texture: 0 },
    { variation: 15, undershirt: 57, torso: 15, texture: 0 },
    { variation: 16, undershirt: 57, torso: 0, texture: 0 },
    { variation: 17, undershirt: 57, torso: 114, texture: 0 },
    { variation: 18, undershirt: 57, torso: 0, texture: 0 },
    { variation: 21, undershirt: 57, torso: 2, texture: 0 },
    { variation: 22, undershirt: 57, torso: 0, texture: 0 },
    { variation: 25, undershirt: 57, torso: 21, texture: 0 },
    { variation: 26, undershirt: 57, torso: 0, texture: 0 },
    { variation: 33, undershirt: 57, torso: 0, texture: 0 },
    { variation: 34, undershirt: 57, torso: 0, texture: 0 },
    { variation: 36, undershirt: 57, torso: 114, texture: 0 },
    { variation: 38, undershirt: 57, torso: 48, texture: 0 },
    { variation: 39, undershirt: 57, torso: 0, texture: 0 },
    { variation: 40, undershirt: 57, torso: 21, texture: 0 },
    { variation: 41, undershirt: 57, torso: 22, texture: 0 },
    { variation: 42, undershirt: 57, torso: 11, texture: 0 },
    { variation: 43, undershirt: 57, torso: 11, texture: 0 },
    { variation: 44, undershirt: 57, torso: 0, texture: 0 },
    { variation: 45, undershirt: 57, torso: 21, texture: 0 },
    { variation: 47, undershirt: 57, torso: 0, texture: 0 },
    { variation: 49, undershirt: 57, torso: 1, texture: 0 },
    { variation: 50, undershirt: 57, torso: 1, texture: 0 },
    { variation: 52, undershirt: 57, torso: 1, texture: 0 },
    { variation: 53, undershirt: 57, torso: 1, texture: 0 },
    { variation: 54, undershirt: 57, torso: 1, texture: 0 },
    { variation: 56, undershirt: 57, torso: 0, texture: 0 },
    { variation: 63, undershirt: 57, torso: 0, texture: 0 },
    { variation: 65, undershirt: 57, torso: 1, texture: 0 },
    { variation: 67, undershirt: 57, torso: 1, texture: 0 },
    { variation: 71, undershirt: 57, torso: 0, texture: 0 },
    { variation: 73, undershirt: 57, torso: 0, texture: 0 },
    { variation: 74, undershirt: 57, torso: 1, texture: 0 },
    { variation: 78, undershirt: 57, torso: 1, texture: 0 },
    { variation: 79, undershirt: 57, torso: 1, texture: 0 },
    { variation: 80, undershirt: 57, torso: 0, texture: 0 },
    { variation: 81, undershirt: 57, torso: 0, texture: 0 },
    { variation: 82, undershirt: 57, torso: 0, texture: 0 },
    { variation: 83, undershirt: 57, torso: 0, texture: 0 },
    { variation: 85, undershirt: 57, torso: 1, texture: 0 },
    { variation: 89, undershirt: 57, torso: 1, texture: 0 },
    { variation: 92, undershirt: 57, torso: 12, texture: 0 },
    { variation: 93, undershirt: 57, torso: 0, texture: 0 },
    { variation: 94, undershirt: 57, torso: 0, texture: 0 },
    { variation: 95, undershirt: 57, torso: 0, texture: 0 },
    { variation: 97, undershirt: 57, torso: 0, texture: 0 },
    { variation: 98, undershirt: 57, torso: 0, texture: 0 },
    { variation: 105, undershirt: 57, torso: 0, texture: 0 },
    { variation: 107, undershirt: 57, torso: 1, texture: 0 },
    { variation: 109, undershirt: 57, torso: 2, texture: 0 },
    { variation: 111, undershirt: 57, torso: 1, texture: 0 },
    { variation: 114, undershirt: 57, torso: 114, texture: 0 },
    { variation: 117, undershirt: 57, torso: 6, texture: 0 },
    { variation: 119, undershirt: 57, torso: 6, texture: 0 },
    { variation: 120, undershirt: 57, torso: 2, texture: 0 },
    { variation: 123, undershirt: 57, torso: 0, texture: 0 },
    { variation: 128, undershirt: 57, torso: 0, texture: 0 },
    { variation: 131, undershirt: 57, torso: 0, texture: 0 },
    { variation: 132, undershirt: 57, torso: 0, texture: 0 },
    { variation: 133, undershirt: 57, torso: 0, texture: 0 },
    { variation: 135, undershirt: 57, torso: 0, texture: 0 },
    { variation: 135, undershirt: 57, torso: 0, texture: 0 },
    { variation: 137, undershirt: 57, torso: 2, texture: 0 },
    { variation: 144, undershirt: 57, torso: 1, texture: 0 },
    { variation: 146, undershirt: 57, torso: 0, texture: 0 },
    { variation: 149, undershirt: 57, torso: 6, texture: 0 },
    { variation: 154, undershirt: 57, torso: 1, texture: 0 },
    { variation: 155, undershirt: 57, torso: 6, texture: 0 },
    { variation: 158, undershirt: 57, torso: 2, texture: 0 },
    { variation: 159, undershirt: 57, torso: 2, texture: 0 },
    { variation: 164, undershirt: 57, torso: 0, texture: 0 },
    { variation: 165, undershirt: 57, torso: 1, texture: 0 },
    { variation: 168, undershirt: 57, torso: 1, texture: 0 },
    { variation: 176, undershirt: 57, torso: 2, texture: 0 },
    { variation: 193, undershirt: 57, torso: 0, texture: 0 },
    { variation: 202, undershirt: 57, torso: 2, texture: 0 },
    { variation: 205, undershirt: 57, torso: 2, texture: 0 },
    { variation: 206, undershirt: 57, torso: 2, texture: 0 },
    { variation: 207, undershirt: 57, torso: 2, texture: 0 },
    { variation: 208, undershirt: 57, torso: 0, texture: 0 },
    { variation: 213, undershirt: 57, torso: 2, texture: 0 },
    { variation: 214, undershirt: 57, torso: 1, texture: 0 },
    { variation: 219, undershirt: 57, torso: 2, texture: 0 },
    { variation: 220, undershirt: 57, torso: 1, texture: 0 },
    { variation: 221, undershirt: 57, torso: 1, texture: 0 },
    { variation: 222, undershirt: 57, torso: 0, texture: 0 },
    { variation: 223, undershirt: 57, torso: 2, texture: 0 },
    { variation: 224, undershirt: 57, torso: 1, texture: 0 },
    { variation: 225, undershirt: 57, torso: 8, texture: 0 },
    { variation: 226, undershirt: 57, torso: 0, texture: 0 },
];

var malePants = [
    { variation: 0, texture: 0 },
    { variation: 1, texture: 0 },
    { variation: 3, texture: 0 },
    { variation: 4, texture: 0 },
    { variation: 5, texture: 0 },
    { variation: 7, texture: 0 },
    { variation: 8, texture: 0 },
    { variation: 9, texture: 0 },
    { variation: 10, texture: 0 },
    { variation: 13, texture: 0 },
    { variation: 19, texture: 0 },
    { variation: 20, texture: 0 },
    { variation: 22, texture: 0 },
    { variation: 23, texture: 0 },
    { variation: 24, texture: 0 },
    { variation: 25, texture: 0 },
    { variation: 26, texture: 0 },
    { variation: 27, texture: 0 },
    { variation: 28, texture: 0 },
    { variation: 29, texture: 0 },
    { variation: 30, texture: 0 },
    { variation: 31, texture: 0 },
    { variation: 32, texture: 0 },
    { variation: 33, texture: 0 },
    { variation: 34, texture: 0 },
    { variation: 35, texture: 0 },
    { variation: 36, texture: 0 },
    { variation: 37, texture: 0 },
    { variation: 38, texture: 0 },
    { variation: 39, texture: 0 },
    { variation: 40, texture: 0 },
    { variation: 41, texture: 0 },
    { variation: 43, texture: 0 },
    { variation: 45, texture: 0 },
    { variation: 46, texture: 0 },
    { variation: 47, texture: 0 },
    { variation: 48, texture: 0 },
    { variation: 49, texture: 0 },
    { variation: 50, texture: 0 },
    { variation: 51, texture: 0 },
    { variation: 52, texture: 0 },
    { variation: 53, texture: 0 },
    { variation: 55, texture: 0 },
    { variation: 58, texture: 0 },
    { variation: 60, texture: 0 },
    { variation: 63, texture: 0 },
    { variation: 64, texture: 0 },
    { variation: 65, texture: 0 },
    { variation: 66, texture: 0 },
    { variation: 67, texture: 0 },
    { variation: 68, texture: 0 },
    { variation: 69, texture: 0 },
    { variation: 70, texture: 0 },
    { variation: 71, texture: 0 },
    { variation: 73, texture: 0 },
    { variation: 75, texture: 0 },
    { variation: 76, texture: 0 },
    { variation: 77, texture: 0 },
    { variation: 78, texture: 0 },
    { variation: 79, texture: 0 },
    { variation: 82, texture: 0 },
    { variation: 83, texture: 0 },
    { variation: 84, texture: 0 },
    { variation: 85, texture: 0 },
];

var maleShorts = [
    { variation: 2, texture: 0 },
    { variation: 12, texture: 0 },
    { variation: 14, texture: 0 },
    { variation: 15, texture: 0 },
    { variation: 16, texture: 0 },
    { variation: 17, texture: 0 },
    { variation: 18, texture: 0 },
    { variation: 21, texture: 0 },
    { variation: 56, texture: 0 },
    { variation: 61, texture: 0 },
    { variation: 80, texture: 0 },
    { variation: 81, texture: 0 },
];

var maleShoes = [
    { variation: 3, texture: 0 },
    { variation: 10, texture: 0 },
    { variation: 15, texture: 0 },
    { variation: 17, texture: 0 },
    { variation: 18, texture: 0 },
    { variation: 19, texture: 0 },
    { variation: 20, texture: 0 },
    { variation: 21, texture: 0 },
    { variation: 36, texture: 0 },
    { variation: 37, texture: 0 },
    { variation: 38, texture: 0 },
    { variation: 40, texture: 0 },
    { variation: 41, texture: 0 },
    { variation: 44, texture: 0 },
    { variation: 45, texture: 0 },
    { variation: 51, texture: 0 },
    { variation: 52, texture: 0 },
    { variation: 53, texture: 0 },
    { variation: 54, texture: 0 },
    { variation: 56, texture: 0 },
];

var maleSneakers = [
    { variation: 0, texture: 0 },
    { variation: 1, texture: 0 },
    { variation: 2, texture: 0 },
    { variation: 4, texture: 0 },
    { variation: 7, texture: 0 },
    { variation: 8, texture: 0 },
    { variation: 9, texture: 0 },
    { variation: 11, texture: 0 },
    { variation: 12, texture: 0 },
    { variation: 14, texture: 0 },
    { variation: 22, texture: 0 },
    { variation: 23, texture: 0 },
    { variation: 24, texture: 0 },
    { variation: 25, texture: 0 },
    { variation: 26, texture: 0 },
    { variation: 27, texture: 0 },
    { variation: 28, texture: 0 },
    { variation: 29, texture: 0 },
    { variation: 30, texture: 0 },
    { variation: 31, texture: 0 },
    { variation: 32, texture: 0 },
    { variation: 35, texture: 0 },
    { variation: 42, texture: 0 },
    { variation: 43, texture: 0 },
    { variation: 46, texture: 0 },
    { variation: 47, texture: 0 },
    { variation: 48, texture: 0 },
    { variation: 49, texture: 0 },
    { variation: 55, texture: 0 },
    { variation: 57, texture: 0 },
    { variation: 58, texture: 0 },
];

var maleSandals = [
    { variation: 5, texture: 0 },
    { variation: 6, texture: 0 },
    { variation: 16, texture: 0 },
    { variation: 34, texture: 0 },
];

var maleTies = [
    { variation: 0, texture: 0 },
    { variation: 10, texture: 0 },
    { variation: 11, texture: 0 },
    { variation: 12, texture: 0 },
    { variation: 18, texture: 0 },
    { variation: 19, texture: 0 },
    { variation: 20, texture: 0 },
    { variation: 21, texture: 0 },
    { variation: 22, texture: 0 },
    { variation: 23, texture: 0 },
    { variation: 24, texture: 0 },
    { variation: 25, texture: 0 },
    { variation: 28, texture: 0 },
    { variation: 29, texture: 0 },
    { variation: 32, texture: 0 },
    { variation: 36, texture: 0 },
    { variation: 37, texture: 0 },
    { variation: 38, texture: 0 },
    { variation: 39, texture: 0 },
    { variation: 115, texture: 0 },
    { variation: 117, texture: 0 },
    { variation: 118, texture: 0 },
];

var maleScarfs = [
    { variation: 0, texture: 0 },
    { variation: 30, texture: 0 },
    { variation: 31, texture: 0 },
    { variation: 34, texture: 0 },
    { variation: 35, texture: 0 },
    { variation: 112, texture: 0 },
];

var maleCollars = [
    { variation: 0, texture: 0 },
    { variation: 16, texture: 0 },
    { variation: 17, texture: 0 },
    { variation: 42, texture: 0 },
    { variation: 43, texture: 0 },
    { variation: 44, texture: 0 },
    { variation: 45, texture: 0 },
    { variation: 46, texture: 0 },
    { variation: 47, texture: 0 },
    { variation: 48, texture: 0 },
    { variation: 49, texture: 0 },
    { variation: 50, texture: 0 },
    { variation: 51, texture: 0 },
    { variation: 52, texture: 0 },
    { variation: 53, texture: 0 },
    { variation: 54, texture: 0 },
    { variation: 55, texture: 0 },
    { variation: 74, texture: 0 },
    { variation: 75, texture: 0 },
    { variation: 76, texture: 0 },
    { variation: 77, texture: 0 },
    { variation: 78, texture: 0 },
    { variation: 79, texture: 0 },
    { variation: 80, texture: 0 },
    { variation: 81, texture: 0 },
    { variation: 82, texture: 0 },
    { variation: 83, texture: 0 },
    { variation: 85, texture: 0 },
    { variation: 86, texture: 0 },
    { variation: 87, texture: 0 },
    { variation: 88, texture: 0 },
    { variation: 89, texture: 0 },
    { variation: 90, texture: 0 },
    { variation: 91, texture: 0 },
    { variation: 92, texture: 0 },
    { variation: 93, texture: 0 },
    { variation: 94, texture: 0 },
    { variation: 110, texture: 0 },
    { variation: 111, texture: 0 },
    { variation: 113, texture: 0 },
    { variation: 119, texture: 0 },
    { variation: 120, texture: 0 },
    { variation: 121, texture: 0 },
    { variation: 122, texture: 0 },
    { variation: 123, texture: 0 },
];

var maleHeadphones = [
    { variation: 0, texture: 0 },
    { variation: 114, texture: 0 },
    { variation: 124, texture: 0 },
];
